### ISSUE TITLE
问题：微信手机版浏览器按钮无响应

### ISSUE THREAD

**Issue by cyolc932** [Yharimium/hugo-stellar#13]
页面右下角点击打开搜索公告栏的按钮
在微信手机版浏览器内点击无反应

**Comment by Yharimium** [comment]
mathjax 等 js 脚本也是这样。

**Comment by Yharimium** [comment]
目前没有合适的解决方案。请在站点配置文件（`config.yaml`）中添加如下配置：

```
params:
    tencentUrl: true
```

打开此选项后，将自动检查浏览器是否是 qq 和微信的内置浏览器。如果是，则会自动跳转到安全警告页面。效果如下：

![image](https://user-images.githubusercontent.com/97100140/221426323-5f55e826-097b-4e09-ac73-2e8ac15d9bf9.png)

这意味着此网站不可在 qq 和微信的内置浏览器中使用。
