### ISSUE TITLE
问题：排序缩进无法显示

### ISSUE THREAD

**Issue by cyolc932** [Yharimium/hugo-stellar#16]
正常输出：
- 顺序：
  1. 1
  2. 2
  3. 3
 
Markdown：
```markdonw
- 顺序：
  1. 1
  2. 2
  3. 3
```

![图片](https://user-images.githubusercontent.com/46415893/221335333-125d665d-d4ed-4206-9b25-7f56529b6efb.png)

**Comment by Yharimium** [comment]
fixed
