### ISSUE TITLE
Added: folder manager/browser effects page

### ISSUE THREAD

**Issue by cyolc932** [Yharimium/hugo-stellar#20]
![图片](https://user-images.githubusercontent.com/46415893/221586337-da073922-bbb9-484d-b58e-ac82c6f24e01.png)
![图片](https://user-images.githubusercontent.com/46415893/221589049-f630487d-2172-4917-b98f-ebb72b0cfb3a.png)

类似文件夹管理器/浏览器 效果页面，按文件夹分类
应用场景：
 - 减少每篇文章需要写入标签/分类的情况，部分用户几百篇文章
 - 用文件夹可以方便快捷的直接分类，减少重复性操作

参考效果：https://yharim.com/posts/

**Comment by Yharimium** [comment]
在未来的版本中，文件浏览器会单独做一版。
我们会使用开关 `CategoriesByFolder`（默认 `false`）控制按文件夹分类的行为。开启时，categories页面将会按照文件夹而不是文章导言区设置的categories呈现分类。
