### ISSUE TITLE
拓展: 评论插件

### ISSUE THREAD

**Issue by geekswg** [Yharimium/hugo-stellar#27]
主题非常好用，喜欢主题大道至简，已fork。
不过请问下，作者后续，会添加评论插件吗，希望增加 waline.评论插件
[waline](https://waline.js.org/)

**Comment by shenweiyan** [comment]
支持 [giscus](https://giscus.app/zh-CN) 的话也不错

**Comment by Yharimium** [comment]
后续会添加的。可能会添加对 giscus, waline 的支持
