### ISSUE TITLE
Problem: The Doc title is abnormal

### ISSUE THREAD

**Issue by cyolc932** [Yharimium/hugo-stellar#32]
![图片](https://user-images.githubusercontent.com/46415893/228412839-5abe6e34-30c7-4642-a38e-98c1a94d7cef.png)
复现https://doc.dcgg.eu.org/docs/hugodemo/
源码https://github.com/cyolc932/hugo-doc/tree/main/content/docs/HugoDemo

**Comment by shenweiyan** [comment]
https://doc.dcgg.eu.org/docs/avatar.png

**Comment by cyolc932** [comment]
> https://doc.dcgg.eu.org/docs/avatar.png docs 目录下找不到 avatar.png。。。。。

资源文件夹一直存在有avatar.png 已使用其他方案解决
