### ISSUE TITLE
建议：修改主题名称

### ISSUE THREAD

**Issue by shenweiyan** [Yharimium/hugo-stellar#33]
建议修改主题名称为：hugo-theme-stellar（或者 stellar-hugo-theme）

一来可以跟原主题 [hexo-theme-stellar](https://github.com/xaoxuu/hexo-theme-stellar) 一致并有所区别；二来更加鲜明有辨识度。

**Comment by cyolc932** [comment]
上次跟 @Yharimium 讲改名 他说不用了

**Comment by shenweiyan** [comment]
嗯嗯，可以拿过来自己倒腾一个，我就这么干了

**Comment by Yharimium** [comment]
小问题，作者懒癌晚期，不想改
![)V8A2XF{S@ E2RJ_ 2(W HU](https://user-images.githubusercontent.com/97100140/229270977-2acbf7bd-a61b-4dd6-9a25-61d50bce7495.jpg)
